name: Automated donator builds

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
    
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8

      - name: Grant Execute Permissions for Gradlew
        run: chmod +x ./gradlew
# yes this was copied from aseoha
      - name: More gradle
        run: gradle wrapper
      - name: wax on wax off daniel-san
        run: ./gradlew spotlessApply

        
      - name: Build
        run: ./gradlew build
        # env:
        #   BETA: 1 # exclude assets if it's a beta dev build
      - name: Rename artifact with run number
        run: |
          for f in build/libs/*.jar; do
            base="${f%.jar}"
            mv "$f" "${base}-B${{ github.run_number }}-${{ github.ref_name }}.jar"
          done
    
      - name: Publish artifacts
        uses: DrTheodor/discord-webhook-upload-action@v0.2
        with:
          url: ${{ secrets.DEV_BUILDS }}
          file: 'build/libs/*'
          username: TheMaster
          avatar: 'https://media.forgecdn.net/avatars/thumbnails/983/766/256/256/638492366759883163.png'
          commit: '> :sparkles: [%MESSAGE%](<%LINK%>) by [%AUTHOR%](<%AUTHOR_LINK%>) '
          message: |
            <:new1:1253371736510959636><:new2:1253371805734015006> New `Through Time and Space` dev build `#${{ github.run_number }}`:
            %COMMITS%
